# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnelbyte < Formula
  desc "Pay-per-use WireGuard tunnels from your terminal."
  homepage "https://tunnelbyte.dev"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.1/tunnelbyte_0.1.1_darwin_x86_64.tar.gz"
      sha256 "0ab8d72f1a62c02c41e96c2d18171fa7c58bfe875760bb5364a8c595104667d9"

      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.1/tunnelbyte_0.1.1_darwin_arm64.tar.gz"
      sha256 "94a1b59a1320b826a6085d181c5a2b98bf1c9f767e207220c7d840db7b7b634e"

      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.1/tunnelbyte_0.1.1_linux_x86_64.tar.gz"
      sha256 "701a8c07db409f9aed3eaf7a71593719c33e67a2c7a929bbf728ffe459b7e855"
      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.1/tunnelbyte_0.1.1_linux_arm64.tar.gz"
      sha256 "504584b4e3695a5bee07989125627e541cabc8102fbf433bc086139cf610cdd7"
      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
  end

  test do
    assert_match "tunnelbyte", shell_output("#{bin}/tunnelbyte version")
  end
end
