# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnelbyte < Formula
  desc "Pay-per-use WireGuard tunnels from your terminal."
  homepage "https://tunnelbyte.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.0/tunnelbyte_0.1.0_darwin_x86_64.tar.gz"
      sha256 "67dc3c0557b253302b2d8319e22f8367dd63ea1923589afbf986198af6365e79"

      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.0/tunnelbyte_0.1.0_darwin_arm64.tar.gz"
      sha256 "e504a0715fb806bb8026ba91011f79efbabbcee8c6e75de3bc9a61259a08fcd1"

      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.0/tunnelbyte_0.1.0_linux_x86_64.tar.gz"
      sha256 "5432769ae6e8f7f2760447e855eca5ed369b76fe35e3ac13cccbed6ac93bd369"
      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.1.0/tunnelbyte_0.1.0_linux_arm64.tar.gz"
      sha256 "d501da198e354e05a638a5628f315102201df00046c96f5b8a82aa2e02bdc215"
      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
  end

  test do
    assert_match "tunnelbyte", shell_output("#{bin}/tunnelbyte version")
  end
end
