# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnelbyte < Formula
  desc "Pay-per-use WireGuard tunnels from your terminal."
  homepage "https://tunnelbyte.dev"
  version "0.0.1"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.0.1/tunnelbyte_0.0.1_darwin_x86_64.tar.gz"
      sha256 "2daf43f0954114e8bf750f5bea3a14dcf03ecbe5932e7cf50141c9ca8f905603"

      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.0.1/tunnelbyte_0.0.1_darwin_arm64.tar.gz"
      sha256 "1e0d7345b5271a135be2a1eefa1eaa6058d938c6fae75aa4fce0443a5295c44a"

      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.0.1/tunnelbyte_0.0.1_linux_x86_64.tar.gz"
      sha256 "98ec0160eb4a52aca29b00e9cdedc6f615d94b39c7f8edbf9e9487f3276c5c05"
      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunnelbyte/tunnelbyte/releases/download/v0.0.1/tunnelbyte_0.0.1_linux_arm64.tar.gz"
      sha256 "3efd163ad74d9f14e9786e2ac007f04e5bad64c8313db9cd6ecb1b05c373c175"
      define_method(:install) do
        bin.install "tunnelbyte"
      end
    end
  end

  test do
    assert_match "tunnelbyte", shell_output("#{bin}/tunnelbyte version")
  end
end
